---
abstract: 'Check Taiawn SCSB bank info'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-Bank-SCSB-TW
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  HTML::Selector::XPath: 0
  HTML::TreeBuilder::XPath: 0
  List::MoreUtils: 0
  WWW::Mechanize: 1.50
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.11
